### PR TITLE
output-filter: Include strsafe.h after windows.h.

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by jp9000** [comment]
How did you end up with a compiler error? I don't see this error.

**Comment by Biswa96** [comment]
I have used MSYS2/MinGW-w64 toolchain. Including strsafe.h first shows many error due to unknown types in that header file which are in windoows.h or winbase.h.

**Comment by Biswa96** [comment]
I have used MSYS2/MinGW-w64 toolchain. Including strsafe.h first shows many error due to unknown types in that header file which are in windows.h or winbase.h.

**Comment by jp9000** [comment]
Oh I see, it was in your commit message -- my apologies.

**Pull request merged**
