### PR TITLE
when camera is used by other process ，Running control the hr maybe 0x800705AA

### PR DESCRIPTION
**Pull request by wanhongqing123**
### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by wanhongqing123** [comment]
no files

**Comment by jp9000** [comment]
This PR doesn't make any sense. The code is bad and it seems like you're trying to fill out an issue report rather than a PR.

**Comment by wanhongqing123** [comment]
Result HDevice::Start()
{
	HRESULT hr;

	if (!EnsureInitialized(L"Start") || !EnsureInactive(L"Start"))
		return Result::Error;

	if (!!rocketEncoder)
		Sleep(ROCKET_WAIT_TIME_MS);

	hr = control->Run();

	if (FAILED(hr)) {
		if (hr == (HRESULT)0x8007001F || hr == (HRESULT)0x800705AA) {
			WarningHR(L"Run failed, device already in use", hr);
			return Result::InUse;
		} else {
			WarningHR(L"Run failed", hr);
			return Result::Error;
		}
	}

	active = true;
	return Result::Success;
}

**Comment by walker-WSH** [comment]
I also find this issue that so many logitech cameras returns 0x800705AA when it is being used by others.
Related issue link : https://github.com/obsproject/obs-studio/issues/4255

**Pull request closed without merging**
